#ifndef OSM_FFI_CLIENT_H
#define OSM_FFI_CLIENT_H

#include <string>

// Qt-free lazy loader for liblogos_osm.so (the Rust OSM SDK core). The module
// impl is authored against the `universal` interface, which keeps module code
// Qt-free (std::string, dlopen/dlsym) — the Qt plugin glue is generated by
// logos-module-builder. The library path can be overridden with
// LOGOS_OSM_FFI_PATH; otherwise the loader searches the default library name
// on the system path.
class OsmFfiClient
{
public:
    ~OsmFfiClient();

    // Each call returns the JSON string from the Rust core (never throws;
    // load/symbol errors come back as {"ok":false,"error":...}).
    std::string version();
    std::string invoke(const std::string& name, const std::string& argsJson);

    const std::string& lastError() const { return m_lastErr; }

private:
    using NoArgFn  = char* (*)();
    using FreeFn   = void  (*)(char*);
    using InvokeFn = char* (*)(const char*, const char*);

    bool load();

    void*    m_lib     = nullptr;
    NoArgFn  m_version = nullptr;
    FreeFn   m_free    = nullptr;
    InvokeFn m_invoke  = nullptr;
    bool     m_loaded  = false;
    std::string m_lastErr;
};

#endif // OSM_FFI_CLIENT_H
