//! Deliberate guest-artifact rebuilder.
//!
//! A risc0 guest build is NOT byte-reproducible across machines (dependency
//! source paths land in panic-location metadata), so the repo commits the
//! exact deployed artifact at `methods/osm-host/osm_registry.bin` instead of
//! rebuilding it per checkout (see that crate's build.rs). This tool is the
//! one sanctioned way to produce a new artifact:
//!
//! ```text
//! cargo run -p osm-guest-builder --release
//! ```
//!
//! It:
//! 1. builds `methods/osm` for `riscv32im-risc0-zkvm-elf` (via risc0-build,
//!    combining the user ELF with the risc0 kernel into a `ProgramBinary`);
//! 2. copies the combined binary to `methods/osm-host/osm_registry.bin`;
//! 3. prints the program id as both `[u32; 8]` words (to paste into
//!    `methods/osm-host/build.rs`) and hex (for README / docs / STATE.md).
//!
//! After running it, update the pinned id everywhere it is documented and
//! redeploy the program (the id IS the program address on LEZ).

use std::path::PathBuf;

// Generated by build.rs: OSM_REGISTRY_ELF (combined ELF+kernel bytes),
// OSM_REGISTRY_ID ([u32; 8]), OSM_REGISTRY_PATH.
mod guests {
    include!(concat!(env!("OUT_DIR"), "/methods.rs"));
}

fn main() -> anyhow::Result<()> {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let dest = manifest_dir
        .join("../../methods/osm-host/osm_registry.bin")
        .canonicalize()
        .map(|p| p.to_path_buf())
        .unwrap_or_else(|_| {
            // Parent dir may not exist yet on a fresh checkout of this tool.
            let p = manifest_dir.join("../../methods/osm-host/osm_registry.bin");
            std::fs::create_dir_all(p.parent().unwrap()).ok();
            p
        });
    std::fs::write(&dest, guests::OSM_REGISTRY_ELF)?;
    println!("wrote {}", dest.display());

    let words = guests::OSM_REGISTRY_ID;
    let hex_id = words
        .iter()
        .map(|w| format!("{:08x}", w))
        .collect::<String>();
    println!("OSM_REGISTRY_ID (u32 words, paste into methods/osm-host/build.rs):");
    println!("    {words:?}");
    println!("program id (hex, for README/docs/STATE.md): {hex_id}");
    Ok(())
}
