//! Host-side handle to the compiled OSM region-registry guest program.
//!
//! The deployed guest ELF + risc0 kernel are **committed** at
//! `methods/osm-host/osm_registry.bin` and embedded verbatim by `build.rs`
//! (a risc0 guest build is not byte-reproducible across machines, so the
//! artifact — not a per-checkout rebuild — is the program of record; see the
//! build.rs doc comment for the deliberate rebuild procedure). This crate
//! exposes the bytes and their program id so the deployment flow and PDA
//! derivation use the *same* deterministic id that the chain computes from
//! the ELF.
//!
//! ```no_run
//! use lee::program::Program;
//! let program: Program = osm_registry::osm_registry();
//! println!("program id: {:?}", program.id());
//! ```

use std::borrow::Cow;

use lee::program::Program;

// Generated by build.rs from the committed artifact: `OSM_REGISTRY_{ELF,ID}`.
mod guests {
    include!(concat!(env!("OUT_DIR"), "/methods.rs"));
}

/// The embedded OSM-registry program (ELF + deterministic id).
#[must_use]
#[inline]
pub fn osm_registry() -> Program {
    use guests::{OSM_REGISTRY_ELF, OSM_REGISTRY_ID};
    Program::new_unchecked(OSM_REGISTRY_ID, Cow::Borrowed(OSM_REGISTRY_ELF))
}

/// The deterministic program id (`[u32; 8]`) of the embedded guest ELF.
#[must_use]
#[inline]
pub fn osm_registry_id() -> lee::ProgramId {
    use guests::OSM_REGISTRY_ID;
    OSM_REGISTRY_ID
}

/// The embedded guest ELF bytes (what `wallet deploy-program` consumes).
#[must_use]
#[inline]
pub fn osm_registry_elf() -> &'static [u8] {
    use guests::OSM_REGISTRY_ELF;
    OSM_REGISTRY_ELF
}

/// The fixed PDA seed of the registry account, mirrored from the guest
/// (`osm_registry.rs: REGISTRY_SEED`) so the host derives the same account
/// without depending on the guest crate.
pub const REGISTRY_SEED: [u8; 32] = *b"/OSM/REGISTRY/V1/SEED/0000000000";

#[cfg(test)]
mod tests {
    /// The program id documented in README.md / docs/CU_COSTS.md / STATE.md
    /// and asserted by the public-testnet lifecycle test.
    const DOCUMENTED_ID_HEX: &str =
        "77ecdf2f92edfb9eb54c9ae3f5beca1f46b6f9a5d109667b462fd96c7d1c43f0";

    #[test]
    fn program_id_is_stable_and_documented() {
        let id = super::osm_registry_id();
        let hex: String = id.iter().map(|w| format!("{w:08x}")).collect();
        assert_eq!(
            hex, DOCUMENTED_ID_HEX,
            "embedded program id drifted from the documented id — rebuild artifact \
             + update docs together (see build.rs)"
        );
    }

    #[test]
    fn artifact_is_a_real_guest_binary() {
        // ProgramBinary encoding starts with the magic + version word; a
        // truncated or missing artifact must fail loudly here, not at deploy.
        let elf = super::osm_registry_elf();
        assert!(elf.len() > 100_000, "guest artifact implausibly small");
        assert_eq!(elf.len() % 4, 0, "guest artifact not word-aligned");
    }

    #[test]
    fn registry_seed_matches_guest_constant() {
        // The guest pins the same bytes; keep the two in lockstep.
        assert_eq!(super::REGISTRY_SEED, *b"/OSM/REGISTRY/V1/SEED/0000000000");
    }
}
